classdef Building
    properties
        Area
        Name
        Location
        Schedule
        Type
        VariableStruct
    end
    
    methods
        % Constructor
        function obj = Building(name, area, location, schedule, type, ...
                variableStruct)
            obj.Name = name;
            obj.Area = area;
            obj.Location = location;
            obj.Schedule = schedule;
            obj.Type = type;
            if nargin > 5
                obj.VariableStruct = variableStruct;
            else
                obj.VariableStruct = obj.default_variable_struct();
                warning('Default variable struct applied to this Building.')
            end
        end
        
        % Default VariableStruct property for a Building
        function varStruct = default_variable_struct(~)
            varStruct = struct(...
                'AirChangePerHr',           35, ...
                'COP_C',                    1, ...
                'COP_H',                    1, ...
                'Capacitance',              10, ...
                'ColdAirSet',               10, ...
                'Comfort',                  5/3, ...
                'DPset',                    11, ...
                'DailyVariability',         0, ...
                'ExteriorLights',           1, ...
                'ExteriorWallAreaGross',    10000, ...
                'FanPower',                 1, ...
                'HourlyVariability',        0, ...
                'InteriorLights',           10, ...
                'MinDamper',                0.2, ...
                'Orientation',              0, ...
                'Resistance',               600, ...
                'SubHourlyVariability',     0, ...
                'Volume',                   100, ...
                'WaterSystem',              0, ...
                'WindowWallRatio',          0, ...
                'equipment',                0, ...
                'occupancy',                0, ...
                'swDaylighting',            0, ...
                'swDehumid',                0, ...
                'swFixFan',                 0, ...
                'swHvac',                   1, ...
                'swOffPeakHvac',            0 ...
                );
        end
    end
end
